"""Create triangle table

Revision ID: 0d3938ab0865
Revises: 9b8a24f39171
Create Date: 2020-12-21 17:04:17.100802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3938ab0865'
down_revision = '9b8a24f39171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triangles',
                    sa.Column('triangle_id', sa.Integer(), nullable=False),
                    sa.Column('side1', sa.Integer(), nullable=True),
                    sa.Column('side2', sa.Integer(), nullable=True),
                    sa.Column('side3', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('triangle_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triangles')
    # ### end Alembic commands ###
