"""Create diamond table

Revision ID: d3c3eefe5d9f
Revises: 0d3938ab0865
Create Date: 2020-12-21 17:20:30.821736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c3eefe5d9f'
down_revision = '0d3938ab0865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diamonds',
    sa.Column('diamond_id', sa.Integer(), nullable=False),
    sa.Column('diagonal1', sa.Integer(), nullable=True),
    sa.Column('diagonal2', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diamond_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diamonds')
    # ### end Alembic commands ###
