"""Change triangle side to length

Revision ID: f223c4393c1e
Revises: f4c794e6b81c
Create Date: 2020-12-22 05:35:37.555602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f223c4393c1e'
down_revision = 'f4c794e6b81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triangles', sa.Column('length1', sa.Float(), nullable=True))
    op.add_column('triangles', sa.Column('length2', sa.Float(), nullable=True))
    op.add_column('triangles', sa.Column('length3', sa.Float(), nullable=True))
    op.drop_column('triangles', 'side3')
    op.drop_column('triangles', 'side2')
    op.drop_column('triangles', 'side1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triangles', sa.Column('side1', mysql.FLOAT(), nullable=True))
    op.add_column('triangles', sa.Column('side2', mysql.FLOAT(), nullable=True))
    op.add_column('triangles', sa.Column('side3', mysql.FLOAT(), nullable=True))
    op.drop_column('triangles', 'length3')
    op.drop_column('triangles', 'length2')
    op.drop_column('triangles', 'length1')
    # ### end Alembic commands ###
